"""add fields to intern

Revision ID: c4993705aa5c
Revises: e9da37f22793
Create Date: 2026-01-20 17:58:01.015687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4993705aa5c'
down_revision: Union[str, Sequence[str], None] = 'e9da37f22793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intern_profiles', sa.Column('mentor_feedback', sa.Text(), server_default='', nullable=False))
    op.add_column('intern_profiles', sa.Column('ready_for_sale', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intern_profiles', 'ready_for_sale')
    op.drop_column('intern_profiles', 'mentor_feedback')
    # ### end Alembic commands ###
