"""add request

Revision ID: c91bbe757cd4
Revises: c4993705aa5c
Create Date: 2026-01-21 16:55:59.733931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91bbe757cd4'
down_revision: Union[str, Sequence[str], None] = 'c4993705aa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('created', 'in_progress', 'canceled', 'completed', name='request_status'), nullable=False),
    sa.Column('topic', sa.Enum('other', 'give_cv', 'add_to_checks', 'create_aws_acc', 'more_interns_needed', name='request_topic'), nullable=False),
    sa.Column('intern_id', sa.UUID(), nullable=True),
    sa.Column('extra_info', sa.Text(), server_default='', nullable=False),
    sa.Column('comment_from_receiver', sa.Text(), server_default='', nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intern_id'], ['intern_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_id'], ['mentor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['mentor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_requester_id'), 'requests', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_requester_id'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
