"""add birth date

Revision ID: c146ed873fc8
Revises: c91bbe757cd4
Create Date: 2026-01-23 13:25:37.886829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c146ed873fc8'
down_revision: Union[str, Sequence[str], None] = 'c91bbe757cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intern_profiles', sa.Column('birth_date', sa.Date(), nullable=True))
    op.drop_column('intern_profiles', 'age')
    op.drop_index(op.f('ix_requests_requester_id'), table_name='requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_requests_requester_id'), 'requests', ['requester_id'], unique=False)
    op.add_column('intern_profiles', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('intern_profiles', 'birth_date')
    # ### end Alembic commands ###
