"""add intern profile

Revision ID: e7efe0323871
Revises: 16407e8c4938
Create Date: 2026-01-05 14:21:52.392835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7efe0323871'
down_revision: Union[str, Sequence[str], None] = '16407e8c4938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intern_profiles',
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('awaited', 'active', 'paused', 'for_sale', 'sold', 'laid_off', name='internship_status'), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('additional_occupation', sa.Text(), nullable=False),
    sa.Column('employment_status', sa.Enum('student', 'employed', 'unemployed', 'other', name='employment_status'), nullable=False),
    sa.Column('university_name', sa.String(), nullable=False),
    sa.Column('university_course', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('avatar_key', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intern_profiles_email'), 'intern_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_intern_profiles_mentor_id'), 'intern_profiles', ['mentor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intern_profiles_mentor_id'), table_name='intern_profiles')
    op.drop_index(op.f('ix_intern_profiles_email'), table_name='intern_profiles')
    op.drop_table('intern_profiles')
    # ### end Alembic commands ###
